import fs from 'node:fs/promises';
import path from 'node:path';
import { getNovelsDir } from '../config/index.js';
import { isDirtyWorldEntryName, sanitizeWorldEntryName } from '../novel/world-entry-quality.js';

type CliOptions = {
  novelIds: string[];
  outPath?: string;
  lastChapters: number;
  help?: boolean;
};

export type WorldBaselineReportCliOptions = CliOptions;

type RawWorldEntry = {
  id?: string;
  name?: string;
  category?: string;
  tags?: string[];
  qualityScore?: number;
};

type ChapterStat = {
  chapterNumber: number;
  textLength: number;
  mentionsPrev: number;
  mentionsSame: number;
  hasWorldBuilderComment: boolean;
  status: string;
};

export type NovelReport = {
  novelId: string;
  world: {
    totalEntries: number;
    autoExtractedEntries: number;
    autoGeneratedEntries: number;
    dirtyNameEntries: number;
    qualityScoreCoverage: number;
    avgQualityScore: number;
    reusableEntryCount: number;
    reusedEntryCount: number;
    reusedEntryRate: number;
    topReusedEntries: Array<{ name: string; mentionsLater: number }>;
  };
  chapters: {
    observedRange: string;
    analyzedCount: number;
    withPrevWorldMentions: number;
    avgPrevMentionsPerChapter: number;
    stats: ChapterStat[];
  };
};

export type WorldBaselineReportOutput = {
  generatedAt: string;
  options: {
    lastChapters: number;
    novelIds: string[];
  };
  reports: NovelReport[];
};

function parseWorldBaselineReportArgs(argv: string[]): CliOptions {
  const novelIds: string[] = [];
  let outPath: string | undefined;
  let lastChapters = 10;
  let help = false;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--novel' && argv[i + 1]) {
      novelIds.push(argv[i + 1]);
      i += 1;
      continue;
    }
    if (arg === '--out' && argv[i + 1]) {
      outPath = argv[i + 1];
      i += 1;
      continue;
    }
    if (arg === '--last' && argv[i + 1]) {
      const parsed = Number.parseInt(argv[i + 1], 10);
      if (Number.isFinite(parsed) && parsed > 0) {
        lastChapters = parsed;
      }
      i += 1;
      continue;
    }
    if (arg === '--help' || arg === '-h') {
      help = true;
      continue;
    }
  }

  return { novelIds, outPath, lastChapters, help };
}

function formatWorldBaselineReportHelp(invocation = 'npm run report:world-baseline --'): string {
  return [
    `用法: ${invocation} [options]`,
    '',
    '选项:',
    '  --novel <novelId>   仅分析指定小说（可重复多次）',
    '  --out <path>        输出 JSON 文件路径',
    '  --last <count>      仅统计最近 N 章（默认 10）',
    '  -h, --help          显示帮助',
    '',
    '示例:',
    `  ${invocation} --novel <novelId>`,
    `  ${invocation} --novel <novelId> --last 20 --out docs/world-baseline-report.json`,
  ].join('\n');
}

function printWorldBaselineReportHelp(invocation?: string): void {
  console.log(formatWorldBaselineReportHelp(invocation));
}

function parseChapterFromTags(tags: string[]): number | undefined {
  for (const tag of tags) {
    const match = tag.match(/^chapter-(\d+)$/);
    if (!match) continue;
    const chapter = Number.parseInt(match[1], 10);
    if (Number.isFinite(chapter) && chapter > 0) return chapter;
  }
  return undefined;
}

async function listNovelIds(novelsDir: string, preferred: string[]): Promise<string[]> {
  if (preferred.length > 0) return preferred;
  const entries = await fs.readdir(novelsDir, { withFileTypes: true });
  return entries.filter(entry => entry.isDirectory()).map(entry => entry.name).sort();
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function resolveNovelsRoot(baseDir: string): Promise<string> {
  const nestedDir = path.join(baseDir, 'novels');

  if (await exists(nestedDir)) {
    const nestedEntries = await fs.readdir(nestedDir, { withFileTypes: true }).catch(() => []);
    const nestedHasWorld = await Promise.all(
      nestedEntries
        .filter(entry => entry.isDirectory())
        .map(entry => exists(path.join(nestedDir, entry.name, 'world.json'))),
    );
    if (nestedHasWorld.some(Boolean)) return nestedDir;
  }

  return baseDir;
}

async function safeReadText(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, 'utf-8');
  } catch {
    return '';
  }
}

function toFixed3(value: number): number {
  return Number(value.toFixed(3));
}

async function buildNovelReport(novelsRoot: string, novelId: string, lastChapters: number): Promise<NovelReport> {
  const novelDir = path.join(novelsRoot, novelId);
  const worldPath = path.join(novelDir, 'world.json');
  const chaptersDir = path.join(novelDir, 'chapters');

  const worldRaw = await safeReadText(worldPath);
  const worldEntries = (worldRaw ? JSON.parse(worldRaw) : []) as RawWorldEntry[];

  const chapterFiles = await fs.readdir(chaptersDir).catch(() => [] as string[]);
  const chapterNumbers = chapterFiles
    .filter(file => file.endsWith('.md'))
    .map(file => Number.parseInt(path.parse(file).name, 10))
    .filter(num => Number.isFinite(num) && num > 0)
    .sort((a, b) => a - b);

  const recentNumbers = chapterNumbers.slice(-lastChapters);
  const chapterTextMap = new Map<number, string>();
  const chapterMetaMap = new Map<number, unknown>();

  await Promise.all(recentNumbers.map(async (chapterNumber) => {
    const md = await safeReadText(path.join(chaptersDir, `${String(chapterNumber).padStart(3, '0')}.md`));
    chapterTextMap.set(chapterNumber, md);
    const metaRaw = await safeReadText(path.join(chaptersDir, `${String(chapterNumber).padStart(3, '0')}.json`));
    chapterMetaMap.set(chapterNumber, metaRaw ? JSON.parse(metaRaw) : {});
  }));

  const normalizedEntries = worldEntries.map((entry) => {
    const name = (entry.name ?? '').trim();
    const tags = entry.tags ?? [];
    const sourceChapter = parseChapterFromTags(tags);
    const cleanName = sanitizeWorldEntryName(name);
    const dirty = isDirtyWorldEntryName(name) || cleanName !== name;
    return {
      name: cleanName || name,
      tags,
      sourceChapter,
      dirty,
      qualityScore: typeof entry.qualityScore === 'number' ? entry.qualityScore : undefined,
      autoExtracted: tags.includes('auto-extracted'),
      autoGenerated: tags.includes('auto-generated'),
    };
  }).filter(entry => entry.name.length > 0);

  const chapterStats: ChapterStat[] = [];
  const withPrevMentions = { count: 0 };
  let prevMentionTotal = 0;

  for (const chapterNumber of recentNumbers) {
    const content = chapterTextMap.get(chapterNumber) ?? '';
    const meta = chapterMetaMap.get(chapterNumber) as {
      agentComments?: Array<{ agentRole?: string }>;
      status?: string;
    } | undefined;
    const mentionsPrev = normalizedEntries
      .filter(entry => !entry.dirty && entry.sourceChapter !== undefined && entry.sourceChapter < chapterNumber)
      .filter(entry => content.includes(entry.name)).length;
    const mentionsSame = normalizedEntries
      .filter(entry => !entry.dirty && entry.sourceChapter === chapterNumber)
      .filter(entry => content.includes(entry.name)).length;
    const hasWorldBuilderComment = Array.isArray(meta?.agentComments)
      && meta.agentComments.some((item) => item?.agentRole === 'world-builder');

    if (mentionsPrev > 0) withPrevMentions.count += 1;
    prevMentionTotal += mentionsPrev;

    chapterStats.push({
      chapterNumber,
      textLength: content.length,
      mentionsPrev,
      mentionsSame,
      hasWorldBuilderComment,
      status: typeof meta?.status === 'string' ? meta.status : 'unknown',
    });
  }

  const reusableEntries = normalizedEntries.filter(entry => !entry.dirty && entry.sourceChapter !== undefined);

  const chapterCache = new Map<number, string>();
  async function getChapterContent(chapterNumber: number): Promise<string> {
    if (!chapterCache.has(chapterNumber)) {
      const content = await safeReadText(path.join(chaptersDir, `${String(chapterNumber).padStart(3, '0')}.md`));
      chapterCache.set(chapterNumber, content);
    }
    return chapterCache.get(chapterNumber) ?? '';
  }

  const reuseCounter: Array<{ name: string; mentionsLater: number }> = [];
  let reusedEntryCount = 0;
  for (const entry of reusableEntries) {
    let hits = 0;
    for (const chapterNumber of chapterNumbers) {
      if (chapterNumber <= (entry.sourceChapter as number)) continue;
      const content = await getChapterContent(chapterNumber);
      if (content.includes(entry.name)) hits += 1;
    }
    if (hits > 0) reusedEntryCount += 1;
    reuseCounter.push({ name: entry.name, mentionsLater: hits });
  }
  reuseCounter.sort((a, b) => b.mentionsLater - a.mentionsLater);

  const qualityValues = normalizedEntries
    .map(entry => entry.qualityScore)
    .filter((score): score is number => typeof score === 'number');

  return {
    novelId,
    world: {
      totalEntries: normalizedEntries.length,
      autoExtractedEntries: normalizedEntries.filter(entry => entry.autoExtracted).length,
      autoGeneratedEntries: normalizedEntries.filter(entry => entry.autoGenerated).length,
      dirtyNameEntries: normalizedEntries.filter(entry => entry.dirty).length,
      qualityScoreCoverage: normalizedEntries.length === 0
        ? 0
        : toFixed3(qualityValues.length / normalizedEntries.length),
      avgQualityScore: qualityValues.length === 0
        ? 0
        : toFixed3(qualityValues.reduce((sum, value) => sum + value, 0) / qualityValues.length),
      reusableEntryCount: reusableEntries.length,
      reusedEntryCount,
      reusedEntryRate: reusableEntries.length === 0 ? 0 : toFixed3(reusedEntryCount / reusableEntries.length),
      topReusedEntries: reuseCounter.slice(0, 10),
    },
    chapters: {
      observedRange: recentNumbers.length > 0
        ? `${recentNumbers[0]}-${recentNumbers[recentNumbers.length - 1]}`
        : 'none',
      analyzedCount: recentNumbers.length,
      withPrevWorldMentions: withPrevMentions.count,
      avgPrevMentionsPerChapter: recentNumbers.length === 0 ? 0 : toFixed3(prevMentionTotal / recentNumbers.length),
      stats: chapterStats,
    },
  };
}

export async function executeWorldBaselineReport(options: CliOptions): Promise<WorldBaselineReportOutput> {
  const novelsRoot = await resolveNovelsRoot(getNovelsDir());
  const novelIds = await listNovelIds(novelsRoot, options.novelIds);

  const reports: NovelReport[] = [];
  for (const novelId of novelIds) {
    try {
      const report = await buildNovelReport(novelsRoot, novelId, options.lastChapters);
      reports.push(report);
    } catch (error) {
      console.warn(`[world-baseline] 跳过小说 ${novelId}:`, error instanceof Error ? error.message : String(error));
    }
  }

  const output: WorldBaselineReportOutput = {
    generatedAt: new Date().toISOString(),
    options: {
      lastChapters: options.lastChapters,
      novelIds: options.novelIds,
    },
    reports,
  };

  const content = `${JSON.stringify(output, null, 2)}\n`;
  if (options.outPath) {
    const absOutPath = path.resolve(options.outPath);
    await fs.mkdir(path.dirname(absOutPath), { recursive: true });
    await fs.writeFile(absOutPath, content, 'utf-8');
  }
  return output;
}

export async function runWorldBaselineReportCli(
  argv: string[] = process.argv.slice(2),
  invocation = 'npm run report:world-baseline --',
): Promise<number> {
  const options = parseWorldBaselineReportArgs(argv);
  if (options.help) {
    printWorldBaselineReportHelp(invocation);
    return 0;
  }

  const output = await executeWorldBaselineReport(options);
  process.stdout.write(`${JSON.stringify(output, null, 2)}\n`);
  return 0;
}

async function main(): Promise<void> {
  process.exitCode = await runWorldBaselineReportCli();
}

function isExecutedAsEntry(): boolean {
  const argv1 = process.argv[1];
  if (!argv1) return false;
  return path.basename(argv1).includes('world-baseline-report');
}

if (isExecutedAsEntry()) {
  void main().catch((err) => {
    console.error('[world-baseline-report] fatal:', err);
    process.exit(1);
  });
}
