import type { DetectorRule } from './evolvable-detector-types.js';

export const DEFAULT_DIALOGUE_PACING_RULES: DetectorRule[] = [
  {
    id: 'dialogue-ratio-high',
    name: '对话占比过高',
    description: '对话占比超过55%，建议增加动作描写和环境烘托',
    category: 'pacing',
    severity: 'warn',
    enabled: true,
    priority: 1,
    threshold: 0.55,
    weight: 1.0,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'dialogue-ratio-low',
    name: '对话占比过低',
    description: '对话占比低于10%，建议增加角色对话互动',
    category: 'pacing',
    severity: 'warn',
    enabled: true,
    priority: 1,
    threshold: 0.1,
    weight: 1.0,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'dialogue-monologue',
    name: '连续大段对话',
    description: '存在多处连续大段对话，建议穿插动作和心理描写',
    category: 'dialogue',
    severity: 'warn',
    enabled: true,
    priority: 2,
    threshold: 2,
    weight: 0.8,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'said-bookism',
    name: '对话标签病',
    description: '"XX道""XX说"等对话标签过于密集',
    category: 'dialogue',
    severity: 'warn',
    enabled: true,
    priority: 3,
    threshold: 5,
    weight: 0.7,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'action-ratio-low',
    name: '动作描写偏少',
    description: '动作描写占比偏低，场景画面感不足',
    category: 'pacing',
    severity: 'warn',
    enabled: true,
    priority: 4,
    threshold: 0.08,
    weight: 0.6,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'description-ratio-high',
    name: '环境描写偏多',
    description: '环境描写占比过高，建议精简并聚焦剧情推进',
    category: 'pacing',
    severity: 'warn',
    enabled: true,
    priority: 4,
    threshold: 0.35,
    weight: 0.6,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'paragraph-too-short',
    name: '段落过短（碎片化）',
    description: '段落平均长度过短，叙事碎片化严重',
    category: 'structure',
    severity: 'warn',
    enabled: true,
    priority: 5,
    threshold: 25,
    weight: 0.5,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'paragraph-too-long',
    name: '段落过长（压抑感）',
    description: '段落平均长度过长，阅读压力大',
    category: 'structure',
    severity: 'warn',
    enabled: true,
    priority: 5,
    threshold: 200,
    weight: 0.5,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
  {
    id: 'pacing-monotony',
    name: '节奏单调',
    description: '连续多章节奏分布高度相似，易产生阅读疲劳',
    category: 'pacing',
    severity: 'warn',
    enabled: true,
    priority: 3,
    threshold: 0.85,
    weight: 0.7,
    hitCount: 0,
    falsePositiveCount: 0,
    truePositiveCount: 0,
    lastUpdated: Date.now(),
  },
];
