import type { TopicProfile } from './topic-profiles.js';

export const SHOWBIZ_TOPIC_PROFILE: TopicProfile = {
  id: 'showbiz',
  priority: 108,
  genreFocus: 'showbiz',
  patterns: [/(娱乐圈|影帝|影后|顶流|试镜|热搜|剧组|番位|综艺|经纪人|片场|导演组|塌房|翻红|爆红|代言|体验官)/],
  requiredPayoffKeywords: [
    '试镜',
    '角色',
    '热搜',
    '资源',
    '站队',
    '翻红',
    '爆红',
    '通告',
    '番位',
    '压戏',
    '截胡',
    '避雷',
    '预警',
    '排雷',
    '公开验证',
    '签约暂停',
    '体验官',
    '质检报告',
    '供应链清单',
  ],
  requiredSceneKeywords: [
    '片场',
    '试镜间',
    '导演组',
    '节目组',
    '直播',
    '微博',
    '评论区',
    '录制现场',
    '定妆',
    '后台',
    '签约台',
    '弹幕墙',
    '发布会',
    '官宣',
    '代言',
  ],
  suspenseDriftKeywords: ['真相', '秘密', '线索', '调查', '监控', '匿名', '幕后', '删评', '暗网', '爆料来源', '取证', '跟拍'],
  maxSuspenseShare: 0.4,
  directionHint: '娱乐圈题材必须优先兑现资源争夺、试镜输赢、公开预警避雷、舆论起爆和站队变化，不得把主线改成调查幕后。',
  openingHint: '开头优先进入试镜、片场、直播、热搜、定妆、签约台或节目组现场，并明确被换角、黑热搜、撤资源、对家抢位、代言塌房倒计时这类现实阻碍。',
  payoffHint: '本章至少兑现一次娱乐圈可见回报：拿到角色、压住对家、热搜起爆、贵人站队、资源反抢、品牌改口、公开避雷、签约暂停或直播起量。',
  antiDriftHint: '黑幕和秘密只能服务娱乐圈公开反杀；若正文主要在删评、监控、匿名短信、跟踪取证或查幕后上打转，说明已经偏成悬疑。',
  forbiddenSubstitutions: [
    { label: '幕后调查 / 匿名线索替代资源推进', keywords: ['匿名', '线索', '查证', '调查', '监控', '跟拍', '偷拍视频', '爆料来源', '黑邮箱'] },
    { label: '私下谈判替代公开战场', keywords: ['休息室', '会客室', '办公室', '私下', '合同', '律师函', '转账', '谈条件'] },
  ],
  preferredEndingFocus: ['公开预警后的热搜结果', '直播/试镜的即时反馈', '资源截胡的下一步', '站队升级', '下一个塌房预警'],
  antiDelayRule: '直播、试镜、热搜、片场机会一旦出现，就必须尽快当章兑现，不能连续几章只写后台准备、倒计时和私下谈判。',
  informationBoundaryRule: '若系统/预警只给出罪名、倒计时或风险级别，正文不得直接扩写成完整黑料档案；金额、地址、公司、转账链等细节必须先有可见来源。',
  delayedPayoff: {
    anchorKeywords: ['直播', '试镜', '热搜', '片场', '定妆', '录制', '资源', '预警', '签约台'],
    executionKeywords: ['冲上热搜', '拿下角色', '定下', '签约暂停', '叫停签约', '改口', '站队', '反抢', '公开验证', '爆了'],
    backstageKeywords: ['休息室', '会客室', '办公室', '后台', '私下'],
  },
  startupHints: {
    title: '娱乐圈公开战场',
    directionHint: '首章必须让娱乐圈主战场可见：试镜、直播、片场、热搜、定妆、签约台或节目组至少落一项，并出现明确资源阻碍。',
    openingHint: '前 800-1000 字内写清主角当下要争的角色/资源/热搜/直播机会，或要叫停的预警签约，以及谁在抢、压、换、撤、倒计时塌房或公开质疑。',
    payoffHint: '首章至少给一次公开结果：角色保住、热搜爬升、直播起量、品牌改口、签约暂停、公开排雷、站队变化或资源反抢。',
  },
  openingRules: [
    { dimension: 'first-screen', instruction: '娱乐圈开篇前段必须进入公开主场景：试镜、片场、直播、热搜、定妆、签约台、节目组至少一项。', priority: 105 },
    { dimension: 'obstacle', instruction: '阻碍必须是可见行业阻力，例如被换角、黑热搜、撤资源、对家抢位、品牌观望、导演组质疑或代言塌房倒计时。', priority: 106 },
    { dimension: 'early-payoff', instruction: '早期回报必须改变角色、资源、热搜、站队、直播数据、品牌态度或签约结果，不能只查到线索。', priority: 107 },
  ],
  startupBlocks: [
    { title: '公开舞台先出危机', summaryTemplate: '开场直接进入试镜、片场、直播、热搜、定妆、签约台或节目组，让主角被换角、压番、黑热搜、撤资源、对家抢位或预警倒计时压住。{anchor0}', location: '片场 / 试镜间 / 直播间 / 热搜现场 / 签约台', tension: 8 },
    { title: '公开反击给结果', summaryTemplate: '主角必须在公开战场上处理{sceneLabel}，让“{payoffLabel}”变成看得见的数据、态度、签约结果或资源变化。{anchor1}', location: '镜头前 / 导演组 / 评论区 / 围观人群 / 签约台', tension: 9 },
    { title: '行业反应接余波', summaryTemplate: '把结果落到导演、经纪人、品牌方、对家、粉丝或评论区的反应上，再用“{endingFocus}”收尾。{anchor2}', location: '片场出口 / 热搜榜单 / 粉圈舆论场', tension: 8 },
  ],
  skillSignals: ['modern'],
  genreAliases: ['showbiz', 'entertainment', 'modern', 'urban'],
  baselineGenre: 'dushi',
};
