/**
 * 商业预设数据 - Agent Skills 商业化预设技能包
 *
 * 本模块包含商业化预设技能的常量定义和相关类型。
 * 这些预设用于快速初始化商业化导向的技能包。
 */

import type { AgentSkillActivation, AgentSkillDefinition, AgentSkillRole, AgentSkillStatus } from './types.js';

/**
 * 商业化技能预设播种结果
 */
export type SeedCommercialPackResult = {
  created: AgentSkillDefinition[];
  updated: AgentSkillDefinition[];
  reused: AgentSkillDefinition[];
  enabledSkillIds: string[];
};

/**
 * 商业化技能包播种模式
 */
export type SeedCommercialPackMode = 'classic' | 'genre-layered';

/**
 * 通用商业化技能预设（适用于所有题材）
 */
export const COMMERCIAL_PACK_PRESETS: Array<{
  name: string;
  description: string;
  instruction: string;
  targetRoles: AgentSkillRole[];
  targetGenres: string[];
  priority: number;
  status: AgentSkillStatus;
  activation: AgentSkillActivation;
  tags: string[];
}> = [
  {
    name: '章尾钩子推进器',
    description: '提升章末留存与追更意愿，优先服务连载收益。',
    instruction: [
      '本章收尾必须满足：',
      '1. 最后 3-6 段出现未完全解决的冲突或新信息。',
      '2. 结尾避免平铺收束，采用"结果已发生但意义未揭示"的处理。',
      '3. 禁止模板化收尾句（如"夜色渐深，一切归于平静"）。',
      '4. 若本章没有主冲突推进，必须在结尾补充明确的下章行动诱因。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['*'],
    priority: 90,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'retention', 'chapter-hook'],
  },
  {
    name: '反模板化表达',
    description: '降低 AI 味，增加句式和叙事纹理差异。',
    instruction: [
      '写作时执行去模板化约束：',
      '1. 连续三段不得以同类句式开头。',
      '2. 同义高频词避免在 300 字内重复三次以上。',
      '3. 抽象总结句应少于具象动作/感官句。',
      '4. 对关键场景至少给出一处人物可感知的具体细节。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['*'],
    priority: 88,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'style', 'anti-template'],
  },
  {
    name: '角色台词辨识增强',
    description: '增强角色说话辨识度，提升读者代入与讨论度。',
    instruction: [
      '对话段落必须执行：',
      '1. 主要角色在措辞、语速、句长上保持差异化。',
      '2. 每段对话至少体现一个潜台词目标（试探、掩饰、压迫、拉拢等）。',
      '3. 避免所有角色使用同一书面语风格。',
      '4. 关键对话结束后，补一处行为反馈，防止"只说不演"。',
    ].join('\n'),
    targetRoles: ['writer', 'dialogue-polisher', 'editor'],
    targetGenres: ['*'],
    priority: 86,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'dialogue', 'character'],
  },
  {
    name: '付费点前置铺垫',
    description: '在非付费章节提前埋下价值预期，提高后续转化。',
    instruction: [
      '章节中段到尾段需要至少一处"高价值未兑现承诺"：',
      '1. 给出清晰的风险与收益对价。',
      '2. 明确"下一步行动成本"而非空泛悬念。',
      '3. 在不剧透核心谜底的前提下，让读者知道"继续看会得到什么"。',
      '4. 禁止纯情绪煽动式吊胃口，必须有剧情信息增量。',
    ].join('\n'),
    targetRoles: ['writer', 'editor', 'marketing-writer'],
    targetGenres: ['*'],
    priority: 87,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'conversion', 'paywall'],
  },
  {
    name: '冲突升级节奏器',
    description: '保障章节冲突曲线递进，避免平铺导致掉读。',
    instruction: [
      '单章冲突节奏要求：',
      '1. 开始 20% 给出当章目标与阻力。',
      '2. 中段必须出现一次策略失效或代价提升。',
      '3. 尾段出现不可逆后果或信息反转中的至少一种。',
      '4. 若章节篇幅不足，优先保证"阻力升级 + 代价变化"。',
    ].join('\n'),
    targetRoles: ['writer', 'outline', 'editor'],
    targetGenres: ['*'],
    priority: 85,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'pacing', 'conflict'],
  },
  {
    name: '起点爆款开篇三板斧',
    description: '起点风格开篇：前三章快速建立主角优势、世界规则与核心冲突。',
    instruction: [
      '起点爆款开篇硬约束（适用前 1-3 章）：',
      '1. 第一章必须完成：主角身份确立 + 核心能力/金手指展示 + 首次冲突胜利。',
      '2. 前三章内必须明确：世界等级体系、主角当前位置、短期目标（复仇/崛起/求生）。',
      '3. 每章结尾留钩子：下一级威胁预告、新资源线索、关键人物登场。',
      '4. 节奏要求：开篇 500 字内进入冲突，1500 字内完成首次能力展示。',
      '5. 禁止大段世界观说明，规则通过战斗/对抗场景自然呈现。',
      '6. 主角性格标签化：果断/腹黑/谨慎三选一，通过行动而非独白体现。',
    ].join('\n'),
    targetRoles: ['writer', 'outline', 'editor'],
    targetGenres: ['fantasy', 'xianxia', 'xuanhuan', 'urban'],
    priority: 95,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'qidian', 'opening', 'retention'],
  },
  {
    name: '番茄短爽节奏引擎',
    description: '番茄风格：高频小高潮、即时反馈、情绪密度优先。',
    instruction: [
      '番茄短爽节奏硬约束：',
      '1. 每 800-1200 字必须出现一次小高潮：打脸/逆转/意外收获/敌人震惊。',
      '2. 对话占比 40%-60%，通过对话推进冲突，减少环境与心理描写。',
      '3. 每次冲突必须有即时反馈：获得资源/提升实力/敌人态度转变/旁观者震撼。',
      '4. 章尾钩子强制要求：下章必有更强敌人/更大利益/身份曝光危机。',
      '5. 主角行动逻辑简化：目标明确（变强/复仇/护短），手段直接（硬刚/碾压/打脸）。',
      '6. 配角功能化：捧哏（震惊/质疑）、踩脚石（被打脸）、工具人（送资源/送信息）。',
      '7. 禁止连续 3 段无冲突推进的过渡描写，保持叙事密度。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['urban', 'fantasy', 'xianxia'],
    priority: 95,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'fanqie', 'pacing', 'retention'],
  },
  {
    name: '起点升级体系可视化',
    description: '起点读者偏好：清晰的数值/等级体系，每次升级有明确收益展示。',
    instruction: [
      '起点升级体系硬约束：',
      '1. 建立明确等级阶梯：炼气/筑基/金丹 或 青铜/白银/黄金，每个大境界 3-9 小层级。',
      '2. 每次升级必须量化收益：力量提升倍数、新技能解锁、寿命延长、感知范围扩大。',
      '3. 升级场景标准化：突破描写（天地异象/身体变化） + 能力测试（秒杀旧敌/震慑旁观者）。',
      '4. 资源获取路径清晰：灵石/丹药/功法，每种资源对应明确效果。',
      '5. 战力对比可量化：通过等级差、装备加成、功法品阶给出胜率预期。',
      '6. 每 3-5 章安排一次小突破，每 10-15 章安排一次大境界突破。',
    ].join('\n'),
    targetRoles: ['writer', 'world-builder', 'editor'],
    targetGenres: ['xianxia', 'xuanhuan', 'fantasy'],
    priority: 92,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'qidian', 'progression', 'system'],
  },
  {
    name: '番茄打脸爽点公式',
    description: '番茄核心爽点：装逼打脸循环，旁观者震惊反应放大。',
    instruction: [
      '番茄打脸爽点硬约束：',
      '1. 标准打脸流程：敌人/路人轻视 → 主角隐藏实力 → 关键时刻爆发 → 全场震惊/跪舔。',
      '2. 每次打脸必须有 3 个以上旁观者反应：震惊/后悔/恐惧/讨好，通过对话和动作具象化。',
      '3. 主角装逼台词模板：淡然/霸气/嘲讽三选一，配合碾压式行动。',
      '4. 打脸后立即安排新的轻视者，形成循环：小喽啰 → 小头目 → 大佬 → 更大的大佬。',
      '5. 每章至少 2 次情绪高点：打脸爽 + 获得爽（宝物/美女/追随者/震慑全场）。',
      '6. 禁止主角长篇解释，用实力说话，让配角代为解说（"他竟然是...！"）。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['urban', 'fantasy'],
    priority: 94,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'fanqie', 'faceslap', 'emotion'],
  },
  {
    name: '女频情感张力构建',
    description: '女频核心：情感冲突、人物关系、内心戏与成长弧光。',
    instruction: [
      '女频情感张力硬约束：',
      '1. 每章至少一处情感冲突点：误会/试探/拒绝/和解/心动时刻。',
      '2. 男女主互动必须体现情感进度：陌生 → 好奇 → 心动 → 纠结 → 确认，每次互动推进一步。',
      '3. 内心戏占比 20%-35%，通过细腻的心理活动展现人物情感变化。',
      '4. 配角关系网：闺蜜/情敌/家族，每个配角承担特定情感功能（支持/阻碍/催化）。',
      '5. 成长线索：女主在情感与事业/能力上双线成长，避免纯恋爱脑。',
      '6. 甜虐节奏：甜宠场景后必有小波折，虐心情节后必有补偿性甜蜜。',
      '7. 细节刻画：通过微表情/小动作/环境氛围烘托情感氛围。',
    ].join('\n'),
    targetRoles: ['writer', 'character', 'editor'],
    targetGenres: ['romance', 'modern', 'urban'],
    priority: 93,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'female-oriented', 'emotion', 'romance'],
  },
  {
    name: '世界观深度挖掘器',
    description: '通过细节、规则、历史层次构建可信世界，提升作品厚度。',
    instruction: [
      '世界观深度硬约束：',
      '1. 每 5 章至少新增一条世界规则/历史背景/文化细节，逐步展开世界全貌。',
      '2. 规则一致性：已建立的世界规则必须在后续章节中保持一致并产生影响。',
      '3. 细节落地：抽象设定必须通过具体场景体现（如"等级森严"需通过礼仪/称呼/座次展示）。',
      '4. 历史感：重要地点/组织/家族给出简短历史背景，增加世界厚重感。',
      '5. 文化差异：不同势力/种族/地区在语言/习俗/价值观上有可感知差异。',
      '6. 世界与剧情绑定：世界规则应成为冲突来源或解决方案，而非纯装饰。',
    ].join('\n'),
    targetRoles: ['world-builder', 'writer', 'editor'],
    targetGenres: ['fantasy', 'scifi', 'historical', 'xianxia'],
    priority: 84,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'worldbuilding', 'depth'],
  },
  {
    name: '配角立体化塑造',
    description: '避免工具人化，赋予配角独立动机与成长弧光，提升作品层次。',
    instruction: [
      '配角立体化硬约束：',
      '1. 主要配角（出场 3 次以上）必须有明确动机：不能只为主角服务，要有自己的目标。',
      '2. 配角行为逻辑：基于自身立场做决策，即使帮助主角也应有合理理由（利益/情感/价值观）。',
      '3. 配角成长线：重要配角在故事中应有变化（态度转变/能力提升/认知升级）。',
      '4. 差异化塑造：每个配角在说话方式/行为模式/价值观上有明显区分。',
      '5. 避免脸谱化：反派不能纯粹邪恶，盟友不能无条件忠诚，给出人性化的复杂面。',
      '6. 配角视角：适当通过配角视角展现主角行为的影响，增加叙事层次。',
    ].join('\n'),
    targetRoles: ['character', 'writer', 'editor'],
    targetGenres: ['*'],
    priority: 82,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'character', 'depth'],
  },
  {
    name: '伏笔与回收系统',
    description: '通过伏笔埋设与回收增强叙事密度，提升重读价值与讨论度。',
    instruction: [
      '伏笔与回收硬约束：',
      '1. 每 10 章至少埋设 2-3 个伏笔：人物身份/物品来历/事件真相/能力隐藏。',
      '2. 伏笔分级：近期伏笔（3-5 章回收）、中期伏笔（10-20 章）、长线伏笔（50+ 章）。',
      '3. 回收时机：在读者即将遗忘时回收，制造"原来如此"的惊喜感。',
      '4. 回收方式：通过剧情自然揭示，避免角色突然解释式回收。',
      '5. 伏笔强度：重要伏笔需多次暗示（首次埋设 + 中期提醒 + 最终揭示）。',
      '6. 伏笔清单：作者需维护伏笔列表，确保不遗漏且不过度堆积未回收伏笔。',
    ].join('\n'),
    targetRoles: ['outline', 'writer', 'editor'],
    targetGenres: ['*'],
    priority: 83,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'foreshadowing', 'structure'],
  },
  {
    name: '战斗场面动态化',
    description: '战斗场景避免平铺，通过节奏、策略、代价构建紧张感。',
    instruction: [
      '战斗场面硬约束：',
      '1. 战斗节奏：试探（展示双方能力） → 僵持（策略博弈） → 转折（意外/底牌） → 结局（胜负与代价）。',
      '2. 策略可视化：战斗不能纯拼数值，需体现战术选择（环境利用/弱点针对/配合时机）。',
      '3. 动作具象化：避免"一招制敌"式概括，给出 2-3 个关键动作细节。',
      '4. 代价与后果：胜利需付出代价（受伤/消耗/暴露底牌），失败需有后续影响。',
      '5. 情绪起伏：通过角色内心活动/旁观者反应/环境变化烘托战斗紧张感。',
      '6. 战斗意义：每场战斗需推进剧情（获得资源/改变关系/揭示信息），避免无意义打斗。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['fantasy', 'xianxia', 'xuanhuan', 'scifi', 'urban'],
    priority: 86,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'action', 'pacing'],
  },
  {
    name: '日常场景情感化',
    description: '日常过渡场景通过情感/关系/细节推进，避免无效水文。',
    instruction: [
      '日常场景硬约束：',
      '1. 功能明确：每个日常场景必须承担功能（关系推进/信息铺垫/情感积累/世界展示）。',
      '2. 对话有料：日常对话需包含潜台词/性格展示/关系变化，避免纯闲聊。',
      '3. 细节刻画：通过环境/动作/表情等细节烘托氛围或暗示人物状态。',
      '4. 节奏控制：日常场景篇幅控制在 500-800 字，避免过度拖沓。',
      '5. 情感积累：日常场景用于积累情感基础，为后续冲突做铺垫。',
      '6. 过渡自然：日常场景应自然衔接前后剧情，避免突兀插入。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['*'],
    priority: 80,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'slice-of-life', 'emotion'],
  },
  {
    name: '反派智商在线',
    description: '反派行为符合逻辑，有合理动机与策略，避免降智送人头。',
    instruction: [
      '反派智商硬约束：',
      '1. 动机合理：反派行为基于自身利益/信念/立场，而非"因为是反派所以作恶"。',
      '2. 策略可行：反派计划在其认知范围内合理，失败因主角更强/运气/信息差，非智商崩塌。',
      '3. 避免降智：反派不会明知主角强大还单独送死，不会掌握优势时废话给主角翻盘机会。',
      '4. 信息不对称：反派失败可因不了解主角底牌，但不能因剧情需要突然变蠢。',
      '5. 反派成长：长线反派应随剧情推进调整策略，而非重复失败套路。',
      '6. 人性化：给反派一些人性化时刻（亲情/友情/信念），避免纯粹脸谱化。',
    ].join('\n'),
    targetRoles: ['character', 'writer', 'outline'],
    targetGenres: ['*'],
    priority: 84,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'villain', 'logic'],
  },
  {
    name: '金句与名场面打造',
    description: '打造可传播的金句与名场面，提升作品讨论度与记忆点。',
    instruction: [
      '金句与名场面硬约束：',
      '1. 金句时机：在情感/冲突高潮时植入金句，通过角色台词或叙述呈现。',
      '2. 金句特征：简短有力（10-30 字），体现人物性格/价值观/作品主题。',
      '3. 名场面构建：每 15-20 章打造一个名场面（高燃战斗/情感爆发/身份揭示/重大抉择）。',
      '4. 场面要素：视觉冲击（动作/场景） + 情感共鸣（台词/内心） + 剧情转折（意外/反转）。',
      '5. 传播性：金句与名场面应具备独立传播价值，脱离上下文仍有感染力。',
      '6. 避免堆砌：金句不能频繁出现导致审美疲劳，保持稀缺性与仪式感。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['*'],
    priority: 85,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'memorable', 'viral'],
  },
  {
    name: '多线叙事协调器',
    description: '多条故事线并行推进时保持节奏平衡，避免主次失调。',
    instruction: [
      '多线叙事硬约束：',
      '1. 主线优先：主线（主角成长/核心冲突）占比 60%-70%，支线占比 30%-40%。',
      '2. 切换时机：在一条线索达到小高潮或悬念点时切换，保持读者兴趣。',
      '3. 线索关联：支线应与主线有交集（影响主线/被主线影响/最终汇合），避免完全独立。',
      '4. 节奏平衡：不同线索的节奏应有差异（主线紧张/支线舒缓），形成张弛有度。',
      '5. 篇幅控制：单次支线叙述不超过 1500 字，避免读者遗忘主线。',
      '6. 收束时机：支线应在主线关键节点前收束或汇入，避免拖沓。',
    ].join('\n'),
    targetRoles: ['outline', 'writer', 'editor'],
    targetGenres: ['*'],
    priority: 81,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'multi-thread', 'structure'],
  },
];

/**
 * 题材分层商业化技能预设（针对特定题材）
 */
export const COMMERCIAL_GENRE_LAYERED_PRESETS: Array<{
  name: string;
  description: string;
  instruction: string;
  targetRoles: AgentSkillRole[];
  targetGenres: string[];
  priority: number;
  status: AgentSkillStatus;
  activation: AgentSkillActivation;
  tags: string[];
}> = [
  {
    name: '历史考据与因果链强化',
    description: '面向历史题材，强化史实质感、势力关系与因果递进。',
    instruction: [
      '历史题材执行硬规则：',
      '1. 关键场景至少落一个可验证细节（官职、礼制、地理、军制或时代器物）。',
      '2. 决策必须体现"动机 -> 代价 -> 后果"，避免空洞豪言。',
      '3. 段落推进尽量通过事件与行为，不以口号式抒情代替剧情。',
      '4. 章尾给出下一步政治/军事/家族层面的明确行动触发。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['historical'],
    priority: 93,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'historical'],
  },
  {
    name: '悬疑线索密度与反转节拍',
    description: '面向悬疑题材，增强线索回收与反转节奏，减少平铺叙述。',
    instruction: [
      '悬疑题材执行硬规则：',
      '1. 每章至少新增一条有效线索，并标明其与旧线索的关系。',
      '2. 中后段至少出现一次"预期偏移"（误导修正或视角反证）。',
      '3. 禁止纯信息堆砌，线索必须绑定人物行动与风险升级。',
      '4. 对白占比控制在 10%-35%，避免连续三段全对白或全说明。',
      '5. 每 2-3 段补一个动作或感官落点，避免"只讲不演"。',
      '6. 章尾必须留下可追问的问题，并给出下一章可验证方向。',
    ].join('\n'),
    targetRoles: ['writer', 'editor', 'reader'],
    targetGenres: ['mystery', 'suspense'],
    priority: 93,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'mystery'],
  },
  {
    name: '奇幻规则兑现与代价约束',
    description: '面向奇幻题材，确保设定可兑现，能力使用有代价。',
    instruction: [
      '奇幻题材执行硬规则：',
      '1. 能力/法则出手时，必须同步体现限制或代价，防止"万能解法"。',
      '2. 每章至少推进一条世界规则与主冲突的绑定关系。',
      '3. 高光段落需要"感官细节 + 规则反馈 + 人物选择"三要素。',
      '4. 章尾给出更高层级威胁或新规则揭示，形成追更驱动力。',
    ].join('\n'),
    targetRoles: ['writer', 'editor', 'world-builder'],
    targetGenres: ['fantasy', 'xianxia', 'xuanhuan'],
    priority: 93,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'fantasy'],
  },
  {
    name: '科幻硬核设定自洽',
    description: '面向科幻题材，确保科技设定逻辑自洽，技术展示有说服力。',
    instruction: [
      '科幻题材执行硬规则：',
      '1. 核心科技设定必须建立明确规则：能做什么、不能做什么、代价是什么。',
      '2. 技术展示通过具体应用场景呈现，避免大段理论说明。',
      '3. 科技发展需符合内在逻辑：新技术基于已有设定延伸，不能凭空出现。',
      '4. 社会影响落地：重大科技必须体现对社会结构/伦理/日常生活的影响。',
      '5. 专业术语适度：关键概念给出通俗解释，避免堆砌术语造成阅读障碍。',
      '6. 冲突来源多样化：技术本身的限制、伦理困境、资源争夺、理念冲突。',
    ].join('\n'),
    targetRoles: ['writer', 'world-builder', 'editor'],
    targetGenres: ['scifi'],
    priority: 92,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'scifi'],
  },
  {
    name: '末世生存压迫感营造',
    description: '面向末世题材，通过资源稀缺、环境威胁、人性考验构建压迫感。',
    instruction: [
      '末世题材执行硬规则：',
      '1. 资源系统量化：食物/水/武器/药品建立明确消耗与获取机制。',
      '2. 环境威胁常态化：每 3-5 章出现一次生存危机（丧尸/辐射/极端天气/敌对势力）。',
      '3. 人性选择困境：定期安排道德两难选择（救人 vs 自保/分配资源/信任背叛）。',
      '4. 团队动态演化：幸存者团队关系随资源压力变化（合作/猜忌/分裂/重组）。',
      '5. 希望与绝望平衡：在压抑氛围中穿插小胜利/温情时刻，避免持续负面导致疲劳。',
      '6. 生存技能具象化：通过具体行动展示生存智慧（陷阱制作/伤口处理/物资搜寻）。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['scifi', 'horror'],
    priority: 91,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'apocalypse'],
  },
  {
    name: '游戏异界沉浸式体验',
    description: '面向游戏异界题材，通过系统面板、技能树、副本设计增强代入感。',
    instruction: [
      '游戏异界题材执行硬规则：',
      '1. 系统界面可视化：属性面板/技能描述/任务提示以简洁格式呈现，避免冗长。',
      '2. 升级节奏明确：每 2-3 章安排一次等级提升/技能解锁/装备获取。',
      '3. 副本结构标准化：进入 → 探索（遇敌/解谜） → Boss战 → 奖励结算。',
      '4. 数值成长可感知：战力提升通过对比体现（秒杀曾经的强敌/挑战更高难度）。',
      '5. 游戏机制与剧情融合：系统规则成为冲突来源或解决方案，非纯装饰。',
      '6. 社交系统落地：公会/组队/PK通过具体互动展现，体现玩家生态。',
    ].join('\n'),
    targetRoles: ['writer', 'world-builder', 'editor'],
    targetGenres: ['fantasy', 'urban'],
    priority: 94,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'game-world'],
  },
  {
    name: '重生复仇信息差利用',
    description: '面向重生题材，通过先知优势、蝴蝶效应、因果修正构建张力。',
    instruction: [
      '重生题材执行硬规则：',
      '1. 先知优势具体化：主角利用未来信息获利（股票/彩票/商机/危机预警），每次给出明确收益。',
      '2. 蝴蝶效应递进：主角改变历史后，逐步出现意外变化（原本盟友成敌/新威胁出现）。',
      '3. 复仇节奏分层：小仇当章报（打脸/揭穿），中仇数章布局，大仇作为长线主线。',
      '4. 信息差兑现：主角知道未来风险或机会后，必须立刻转成截胡、避坑、反抢、打脸等可见收益，不能只留下更大的谜团。',
      '5. 因果修正压力：重生改变越大，世界修正力越强，制造新的阻力与代价。',
      '6. 情感二次体验：对前世重要人物的态度转变（珍惜/警惕/补偿/复仇）。',
    ].join('\n'),
    targetRoles: ['writer', 'outline', 'editor'],
    targetGenres: ['urban', 'fantasy', 'romance'],
    priority: 94,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'rebirth'],
  },
  {
    name: '快穿世界切换节奏',
    description: '面向快穿题材，通过世界规则差异、任务目标、情感线索维持新鲜感。',
    instruction: [
      '快穿题材执行硬规则：',
      '1. 世界规则快速建立：每个新世界前 2 章内明确时代背景/身份设定/核心冲突。',
      '2. 任务目标清晰化：系统任务/原主心愿/隐藏目标分层呈现，逐步揭示。',
      '3. 世界风格差异化：连续世界避免同类型（古代 → 现代 → 星际 → 修真），保持新鲜感。',
      '4. 情感线索延续：主线CP在不同世界以不同身份相遇，通过细节暗示前世记忆。',
      '5. 世界完结节奏：单世界 5-15 章，任务完成 → 情感高潮 → 离别/转世。',
      '6. 主线推进：穿越原因/幕后真相/终极目标作为贯穿线索，每个世界推进一步。',
    ].join('\n'),
    targetRoles: ['writer', 'outline', 'editor'],
    targetGenres: ['romance', 'fantasy'],
    priority: 92,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'quick-transmigration'],
  },
  {
    name: '无限流副本设计与团队博弈',
    description: '面向无限流题材，通过副本规则、生存游戏、玩家博弈构建紧张感。',
    instruction: [
      '无限流题材执行硬规则：',
      '1. 副本规则明确：进入时公布核心规则/胜利条件/失败惩罚，规则内允许多种策略。',
      '2. 信息不对称：规则有隐藏条款/NPC有秘密/玩家各怀心思，通过试错逐步揭示。',
      '3. 团队博弈动态：临时队友间的合作/背叛/试探/交易，基于利益与性格做决策。',
      '4. 生存压力递进：副本难度阶梯式提升，死亡威胁真实（配角死亡/主角受伤）。',
      '5. 智力对抗：通过推理/陷阱/心理战解决问题，避免纯武力碾压。',
      '6. 副本节奏：规则解读（1-2章） → 试探博弈（2-3章） → 真相揭示与最终对抗（2-3章）。',
    ].join('\n'),
    targetRoles: ['writer', 'outline', 'editor'],
    targetGenres: ['horror', 'suspense', 'scifi'],
    priority: 93,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'infinite-flow'],
  },
  {
    name: '星际文明与宇宙格局',
    description: '面向星际题材，通过文明冲突、星际政治、宇宙探索构建宏大叙事。',
    instruction: [
      '星际题材执行硬规则：',
      '1. 文明体系分层：建立明确的文明等级/科技树/资源分布/势力版图。',
      '2. 星际政治具象化：联邦/帝国/联盟间的外交/战争/贸易通过具体事件展现。',
      '3. 种族特色差异：不同外星种族在生理/文化/价值观/科技路线上有明显区分。',
      '4. 探索与发现：新星球/遗迹/物种的发现推动剧情，每次探索有风险与收获。',
      '5. 宏观与微观结合：大格局通过小人物视角落地，避免纯粹的势力对抗描写。',
      '6. 科技与人性：探讨科技发展对人性/伦理/社会的影响，增加思想深度。',
    ].join('\n'),
    targetRoles: ['writer', 'world-builder', 'editor'],
    targetGenres: ['scifi'],
    priority: 91,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'space-opera'],
  },
  {
    name: '灵异恐怖氛围营造',
    description: '面向灵异恐怖题材，通过环境渲染、心理压迫、未知恐惧构建惊悚感。',
    instruction: [
      '灵异恐怖题材执行硬规则：',
      '1. 环境渲染细腻：通过光影/声音/气味/温度等感官细节营造压抑氛围。',
      '2. 恐怖节奏控制：张弛有度，惊吓点（jump scare）与持续压迫感（tension）交替。',
      '3. 未知恐惧优先：不要过早揭示鬼怪真面目，通过暗示/局部/侧面描写保持神秘。',
      '4. 心理层面深化：角色的恐惧/疑神疑鬼/理智崩溃过程细腻刻画。',
      '5. 规则建立与打破：灵异现象有规律可循，但关键时刻规则失效制造意外。',
      '6. 生存策略具象：角色应对灵异的方法（符咒/仪式/逃跑/对抗）需有依据。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['horror', 'suspense'],
    priority: 90,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'horror'],
  },
  {
    name: '娱乐圈爽文打脸与逆袭',
    description: '面向娱乐圈题材，通过黑红翻身、作品爆火、全网热议构建爽点。',
    instruction: [
      '娱乐圈题材执行硬规则：',
      '1. 打脸循环：被黑/质疑 → 作品/实力证明 → 全网震惊/黑粉转路人/对家打脸。',
      '2. 作品质量可视化：歌曲/影视/综艺通过数据（播放量/热搜/评分）和反应（业内/观众/媒体）体现。',
      '3. 热搜与舆论：每次事件后给出微博热搜/评论区反应/营销号报道，放大影响力。',
      '4. 人设与真实反差：主角表面人设 vs 真实性格/实力的反差制造惊喜。',
      '5. 圈内关系网：经纪人/导演/前辈/对家/粉丝各方势力的博弈与站队。',
      '6. 逆袭节奏分层：小角色 → 18线 → 3线 → 2线 → 顶流，每个阶段有标志性作品/事件。',
    ].join('\n'),
    targetRoles: ['writer', 'editor'],
    targetGenres: ['urban', 'romance'],
    priority: 93,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'showbiz'],
  },
  {
    name: '种田经营系统化',
    description: '面向种田经营题材，通过资源积累、产业升级、势力扩张构建成就感。',
    instruction: [
      '种田经营题材执行硬规则：',
      '1. 资源系统量化：土地/人口/资金/技术建立明确数值，每次发展有可见增长。',
      '2. 产业链完整：从基础生产（农业/手工业） → 加工 → 贸易 → 产业升级，逻辑自洽。',
      '3. 科技树解锁：新技术/新作物/新工艺的引入有前置条件，逐步解锁带来新玩法。',
      '4. 势力扩张可视：从小村庄 → 城镇 → 城市 → 领地/商业帝国，每个阶段有里程碑事件。',
      '5. 人才招募与培养：关键人才（管家/工匠/谋士）的招募/培养/使用具象化。',
      '6. 外部冲突适度：土匪/商业竞争/官府压力作为调剂，避免纯种田过于平淡。',
    ].join('\n'),
    targetRoles: ['writer', 'world-builder', 'editor'],
    targetGenres: ['historical', 'fantasy', 'urban'],
    priority: 89,
    status: 'active',
    activation: 'manual',
    tags: ['commercial-pack', 'genre-layered', 'farming'],
  },
];

/**
 * 商业化技能结构硬约束
 */
export const COMMERCIAL_STRUCTURE_GUARD = [
  '【结构稳定硬约束】',
  '1. 单章必须覆盖：目标建立 -> 阻力升级 -> 代价变化 -> 章尾推进触发器。',
  '2. 章尾最后 2-4 段必须至少出现一项：人物决策、外部倒计时、关键信息揭示。',
  '3. 禁止以纯抒情/纯总结/纯环境描写收尾；结尾必须新增剧情信息。',
  '4. 篇幅不足时，允许压缩描写，但不得缺失"阻力升级 + 代价变化 + 章尾触发器"。',
].join('\n');
