import type {
  BillingExternalStorefront,
  BillingFreeTrial,
  BillingOperationBindings,
  BillingProductPresentation,
  BillingRechargePackage,
  BillingRule,
  BillingSystemConfig,
} from './types.js';

const DEFAULT_POINT_SCALE = 100;

export const DEFAULT_BILLING_RULES: BillingRule[] = [
  {
    code: 'gen.fast-draft',
    title: '极速草稿',
    description: '适合快速出稿、方向试写和低成本探索。',
    category: 'generation',
    chargeMode: 'per_1k_chars',
    unitPricePoints: 40,
    minPoints: 40,
    enabled: true,
  },
  {
    code: 'gen.standard',
    title: '标准档',
    description: '当前章节生成流程默认使用的计费档位。',
    category: 'generation',
    chargeMode: 'per_1k_chars',
    unitPricePoints: 60,
    minPoints: 60,
    enabled: true,
  },
  {
    code: 'gen.logic-pro',
    title: '逻辑 Pro',
    description: '更强调结构、衔接与一致性的高配档位。',
    category: 'generation',
    chargeMode: 'per_1k_chars',
    unitPricePoints: 100,
    minPoints: 100,
    enabled: true,
  },
  {
    code: 'pkg.kickstart',
    title: '开书包',
    description: '用于从灵感直接生成定位、基础设定、章纲和样章的开书产品包。',
    category: 'package',
    chargeMode: 'package',
    unitPricePoints: 490,
    minPoints: 490,
    enabled: true,
  },
  {
    code: 'pkg.publish-pack',
    title: '发布包装包',
    description: '用于生成书名候选、一句话卖点、短简介和长简介的发布包装产品包。',
    category: 'package',
    chargeMode: 'package',
    unitPricePoints: 49,
    minPoints: 49,
    enabled: true,
  },
  {
    code: 'cap.project-init',
    title: '一键立项包',
    description: '覆盖题材、角色、世界观和大纲种子的立项能力包。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 490,
    minPoints: 490,
    enabled: true,
  },
  {
    code: 'cap.blueprint-100',
    title: '百章蓝图',
    description: '输出长篇章节节奏图与伏笔规划表。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 990,
    minPoints: 990,
    enabled: true,
  },
  {
    code: 'cap.book-audit',
    title: '全书体检',
    description: '面向全书一致性与设定完整性的审查。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 399,
    minPoints: 399,
    enabled: true,
  },
  {
    code: 'cap.foreshadowing-repair',
    title: '伏笔回收重排',
    description: '按卷整理伏笔铺设与回收节奏。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 129,
    minPoints: 129,
    enabled: true,
  },
  {
    code: 'cap.marketing-copy',
    title: '书名与卖点包装',
    description: '生成书名、钩子卖点和短营销文案。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 49,
    minPoints: 49,
    enabled: true,
  },
  {
    code: 'cap.cover-ai',
    title: '封面AI生成',
    description: 'AI 根据作品内容生成封面图片。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 50,
    minPoints: 50,
    enabled: true,
  },
  {
    code: 'cap.cover-prompt',
    title: '封面提示词生成',
    description: 'AI 根据作品内容生成英文图像提示词。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 10,
    minPoints: 10,
    enabled: true,
  },
  {
    code: 'cap.char-portrait',
    title: '角色立绘生成',
    description: 'AI 根据角色信息生成角色立绘图片。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 50,
    minPoints: 50,
    enabled: true,
  },
  {
    code: 'cap.char-portrait-prompt',
    title: '立绘提示词生成',
    description: 'AI 根据角色资料生成英文图像提示词。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 10,
    minPoints: 10,
    enabled: true,
  },
  {
    code: 'cap.polish-intro',
    title: '角色介绍润色',
    description: 'AI 润色角色的人物介绍内容。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 20,
    minPoints: 20,
    enabled: true,
  },
  {
    code: 'gen.side-story',
    title: '番外生成',
    description: 'AI 生成角色番外故事。',
    category: 'generation',
    chargeMode: 'per_1k_chars',
    unitPricePoints: 60,
    minPoints: 60,
    enabled: true,
  },
  {
    code: 'cap.char-chat',
    title: '角色对话',
    description: 'AI 实时角色对话。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 10,
    minPoints: 10,
    enabled: true,
  },
  {
    code: 'cap.expand-idea',
    title: '灵感扩写',
    description: 'AI 将简短创意扩写为详细创作方向。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 20,
    minPoints: 20,
    enabled: true,
  },
  {
    code: 'cap.char-moment',
    title: '角色朋友圈',
    description: 'AI 生成角色朋友圈动态。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 20,
    minPoints: 20,
    enabled: true,
  },
  {
    code: 'cap.comic-panel',
    title: '章节漫画单格',
    description: 'AI 根据章节场景与角色立绘（参考图）生成单格漫画。',
    category: 'capability',
    chargeMode: 'per_call',
    unitPricePoints: 18,
    minPoints: 18,
    enabled: true,
  },
];

export const DEFAULT_BILLING_PACKAGES: BillingRechargePackage[] = [
  {
    id: 'starter-19',
    title: '新手首充',
    amountCny: 19,
    points: 2_000,
    bonusPoints: 200,
    description: '适合首次付费体验和少量章节生成。',
    featured: false,
    enabled: true,
    redemptionGrant: {
      enabled: false,
      title: '',
      quantity: 1,
      pointsPerCode: 100,
      expiresInDays: 30,
      prefix: 'TOPUP',
      remark: '',
    },
  },
  {
    id: 'main-59',
    title: '主力档',
    amountCny: 59,
    points: 6_000,
    bonusPoints: 1_200,
    description: '适合常规写作和日常使用的主力充值档。',
    featured: true,
    enabled: true,
    redemptionGrant: {
      enabled: true,
      title: '充值奖励码',
      quantity: 1,
      pointsPerCode: 500,
      expiresInDays: 30,
      prefix: 'MAIN',
      remark: '充值成功后自动发放。',
    },
  },
  {
    id: 'pro-129',
    title: '高频档',
    amountCny: 129,
    points: 14_000,
    bonusPoints: 3_000,
    description: '适合高频迭代和中重度写作需求。',
    featured: false,
    enabled: true,
    redemptionGrant: {
      enabled: true,
      title: '充值奖励码',
      quantity: 2,
      pointsPerCode: 800,
      expiresInDays: 45,
      prefix: 'PRO',
      remark: '充值成功后自动发放。',
    },
  },
  {
    id: 'studio-299',
    title: '工作室档',
    amountCny: 299,
    points: 36_000,
    bonusPoints: 7_000,
    description: '适合工作室、多项目并行和高强度使用。',
    featured: false,
    enabled: true,
    redemptionGrant: {
      enabled: true,
      title: '充值奖励码',
      quantity: 3,
      pointsPerCode: 1_000,
      expiresInDays: 60,
      prefix: 'STUDIO',
      remark: '充值成功后自动发放。',
    },
  },
];

export const DEFAULT_FREE_TRIAL: BillingFreeTrial = {
  signupGiftPoints: 600,
  firstDayMaxChars: 0,
  firstWeekMaxChars: 0,
  singleChapterMaxChars: 0,
};

export const DEFAULT_BILLING_PRODUCT_PRESENTATION: BillingProductPresentation = {
  chapterBoostTitle: '章节增强包',
};

export const DEFAULT_BILLING_EXTERNAL_STOREFRONT: BillingExternalStorefront = {
  enabled: false,
  providerName: '第三方发卡平台',
  title: '购买兑换码',
  description: '通过第三方发卡平台购买兑换码，购买完成后回到站内兑换积分。',
  buttonText: '前往购买',
  url: '',
  openInNewTab: true,
  notice: '购买成功后复制兑换码，回到积分中心输入兑换码即可到账。',
};

export const DEFAULT_BILLING_OPERATION_BINDINGS: BillingOperationBindings = {
  generateChapterRuleCode: 'gen.standard',
  reviseChapterRuleCode: 'gen.standard',
  resizeChapterRuleCode: 'gen.standard',
  skillGeneratorCostPoints: 99,
  coverAiGenerateRuleCode: 'cap.cover-ai',
  coverAiPromptRuleCode: 'cap.cover-prompt',
  characterPortraitRuleCode: 'cap.char-portrait',
  characterPortraitPromptRuleCode: 'cap.char-portrait-prompt',
  polishCharacterIntroRuleCode: 'cap.polish-intro',
  sideStoryRuleCode: 'gen.side-story',
  characterChatRuleCode: 'cap.char-chat',
  expandIdeaRuleCode: 'cap.expand-idea',
  characterMomentRuleCode: 'cap.char-moment',
  comicPanelRuleCode: 'cap.comic-panel',
};

export function createDefaultBillingConfig(updatedAt: string): BillingSystemConfig {
  return {
    pointScale: DEFAULT_POINT_SCALE,
    trialQuotaChars: 30000,
    freeTrial: DEFAULT_FREE_TRIAL,
    productPresentation: DEFAULT_BILLING_PRODUCT_PRESENTATION,
    externalStorefront: DEFAULT_BILLING_EXTERNAL_STOREFRONT,
    operationBindings: DEFAULT_BILLING_OPERATION_BINDINGS,
    rules: DEFAULT_BILLING_RULES,
    packages: DEFAULT_BILLING_PACKAGES,
    updatedAt,
  };
}
