import type { OperationCenterGroupId } from './shared';

export const OPERATION_CENTER_GROUP_META: Array<{ id: OperationCenterGroupId; label: string }> = [
  { id: 'quick', label: '快速动作' },
  { id: 'layout', label: '布局与视图' },
  { id: 'writing', label: '写作与版本' },
  { id: 'audio', label: '语音与播报' },
  { id: 'quality', label: '质量与清洗' },
];

export const WORKSPACE_COMMAND_SHORTCUT_MAP: Record<string, string> = {
  'open-revise': 'Alt+R',
  'open-command-palette': 'Ctrl+K',
  'open-shortcut-help': '? / F1',
  'find-replace': 'Ctrl+F',
  'chapter-clear-preselect': 'Esc',
  'chapter-prev': 'Alt+[',
  'chapter-next': 'Alt+]',
  'toggle-fullscreen': 'F11',
};

export const WORKSPACE_COMMAND_ALIAS_MAP: Record<string, string[]> = {
  'open-revise': ['xiuding', 'xd', 'revise'],
  'open-command-palette': ['mingling', 'mlmb', 'cmd', 'palette', 'ml'],
  'open-shortcut-help': ['kuaijiejian', 'kjj', 'bangzhu', 'bz', 'hotkey', 'help'],
  'layout-focus': ['zhuanzhu', 'zz', 'focus'],
  'layout-balanced': ['biaozhun', 'bz', 'balanced'],
  'layout-review': ['shenjiao', 'sj', 'review'],
  'toggle-suggestions': ['jianyi', 'jy', 'suggestion'],
  'toggle-fullscreen': ['quanping', 'qp', 'fullscreen'],
  'toggle-comment-panel': ['jianchaqu', 'jcq', 'panel', 'right'],
  'chapter-filter-all': ['zhangjie', 'zj', 'all', 'qb'],
  'chapter-filter-active': ['zhangjie', 'zj', 'active', 'jxz', 'wgdg'],
  'chapter-filter-finalized': ['zhangjie', 'zj', 'finalized', 'ydg'],
  'chapter-filter-clear': ['zhangjie', 'zj', 'clear', 'qingkong', 'qk'],
  'toggle-chapter-density': ['zhangjie', 'zj', 'midu', 'md', 'dense'],
  'chapter-clear-preselect': ['zhangjie', 'zj', 'yuxuan', 'yx', 'clear', 'esc'],
  'chapter-prev': ['shangyizhang', 'syz', 'prev'],
  'chapter-next': ['xiayizhang', 'xyz', 'next'],
  'reset-inspector-width': ['chongzhi', 'cz', 'youce', 'yc', 'width'],
  'batch-generate': ['piliang', 'pl', 'batch'],
  'version-history': ['banben', 'bb', 'history'],
  'plot-explorer': ['juqing', 'jq', 'explore'],
  'dialogue-polish': ['duihua', 'dh', 'polish'],
  'tts-play': ['tts', 'bobao', 'bb'],
  'tts-regenerate': ['tts', 'chonghecheng', 'chhc', 'regenerate'],
  'tts-batch': ['tts', 'batch', 'pl'],
  'command-backfill': ['buchong', 'bc', 'shuohua', 'shr'],
  'command-curate-foreshadowing': ['fubi', 'fb', 'curate'],
  'command-clean-quote': ['yinhao', 'yh', 'clean', 'quote'],
  'find-replace': ['find', 'replace', 'fr', 'chazhao', 'czth'],
};

export const WORKSPACE_OPERATION_CENTER_GROUP_MAP: Record<string, OperationCenterGroupId> = {
  'open-shortcut-help': 'quick',
  'layout-focus': 'layout',
  'layout-balanced': 'layout',
  'layout-review': 'layout',
  'toggle-suggestions': 'layout',
  'toggle-fullscreen': 'layout',
  'reset-inspector-width': 'layout',
  'toggle-comment-panel': 'layout',
  'chapter-filter-all': 'layout',
  'chapter-filter-active': 'layout',
  'chapter-filter-finalized': 'layout',
  'chapter-filter-clear': 'layout',
  'toggle-chapter-density': 'layout',
  'chapter-clear-preselect': 'layout',
  'chapter-prev': 'writing',
  'chapter-next': 'writing',
  'batch-generate': 'writing',
  'version-history': 'writing',
  'plot-explorer': 'writing',
  'dialogue-polish': 'writing',
  'tts-play': 'audio',
  'tts-regenerate': 'audio',
  'tts-batch': 'audio',
  'command-backfill': 'quality',
  'command-curate-foreshadowing': 'quality',
  'command-clean-quote': 'quality',
  'find-replace': 'quality',
};

export const WORKSPACE_COMMAND_KEYWORD_HINT_MAP: Record<string, string[]> = {
  'open-shortcut-help': ['快捷键', '帮助', '总览'],
  'layout-focus': ['布局', '专注'],
  'layout-balanced': ['布局', '标准'],
  'layout-review': ['布局', '审校'],
  'toggle-suggestions': ['建议', '面板'],
  'toggle-fullscreen': ['全屏', 'f11'],
  'reset-inspector-width': ['重置', '右侧', '宽度'],
  'toggle-comment-panel': ['检查区', '右侧', '面板'],
  'chapter-filter-all': ['章节', '筛选', '全部'],
  'chapter-filter-active': ['章节', '筛选', '进行中'],
  'chapter-filter-finalized': ['章节', '筛选', '已定稿'],
  'chapter-filter-clear': ['章节', '筛选', '清空'],
  'toggle-chapter-density': ['章节', '密度', '紧凑'],
  'chapter-clear-preselect': ['章节', '预选', '清除'],
  'chapter-prev': ['章节', '上一章'],
  'chapter-next': ['章节', '下一章'],
  'batch-generate': ['批量', '生成'],
  'version-history': ['版本', '历史', '回滚'],
  'plot-explorer': ['剧情', '探索'],
  'dialogue-polish': ['对话', '打磨'],
  'tts-play': ['tts', '播报'],
  'tts-regenerate': ['tts', '重合成'],
  'tts-batch': ['tts', '批量'],
  'command-backfill': ['补全', '说话人', '标记'],
  'command-curate-foreshadowing': ['伏笔', '梳理'],
  'command-clean-quote': ['清洗', '引号'],
  'find-replace': ['查找', '替换'],
};
